# =============================================================================
# VERSION DU FICHIER DOCKER COMPOSE
# =============================================================================
version: '3.9'  # On utilise la version 3.9 de Docker Compose, qui offre de nombreuses fonctionnalités modernes.


# =============================================================================
# DÉFINITION DES SERVICES
# =============================================================================
services:
  # ---------------------------------------------------------------------------
  # SERVICE FASTAPI
  # ---------------------------------------------------------------------------
  fastapi:
    # Configuration de la construction de l'image pour le service fastapi
    build:
      context: .                  # Contexte de build : le répertoire courant (contenant le Dockerfile et le code source)
      dockerfile: Dockerfile.fastapi  # Nom du Dockerfile spécifique pour construire l'image FastAPI
    ports:
      - "8000:8000"               # Expose le port 8000 du conteneur sur le port 8000 de l'hôte (accès à l'API via localhost:8000)
    volumes:
      - ./data:/app/data          # Monte le dossier local 'data' dans le conteneur à l'emplacement /app/data
                                  # Cela permet de partager et de persister les données entre le conteneur et l'hôte
    networks:
      - eda-net                   # Connecte ce service au réseau nommé "eda-net"


  # ---------------------------------------------------------------------------
  # SERVICE STREAMLIT
  # ---------------------------------------------------------------------------
  streamlit:
    # Configuration de la construction de l'image pour le service streamlit
    build:
      context: .                  # Contexte de build : le répertoire courant
      dockerfile: Dockerfile.streamlit  # Utilise le Dockerfile dédié à Streamlit pour construire l'image
    ports:
      - "8501:8501"               # Expose le port 8501 du conteneur sur le port 8501 de l'hôte (accès à l'interface Streamlit via localhost:8501)
    volumes:
      - ./data:/app/data          # Monte le même dossier 'data' que pour FastAPI afin d'avoir accès aux mêmes fichiers
    depends_on:
      - fastapi                   # Indique que le service Streamlit dépend du service FastAPI.
                                  # Cela garantit que FastAPI démarre avant Streamlit pour que l'API soit disponible dès le lancement
    networks:
      - eda-net                   # Connecte ce service au même réseau "eda-net" pour faciliter la communication entre les services


# =============================================================================
# CONFIGURATION DU RÉSEAU
# =============================================================================
networks:
  eda-net:
    driver: bridge              # Utilise le driver "bridge" par défaut pour le réseau, ce qui permet aux conteneurs de communiquer
